### ISSUE TITLE
can you share the database please? Thank you!

### ISSUE THREAD

**Issue by khancc** [Mahmud0808/Rushly#1]

**Comment by Mahmud0808** [comment]
This project uses Firebase Firestore. Documents will be created automatically when you add new products from the app.

**Comment by khancc** [comment]
sorry for bothering but can you explain how to make an user account become admin? im stuck in creating "admin" collection, what it's collection id, field, type and value? thank you so much!

**Comment by Mahmud0808** [comment]
> im stuck in creating "admin" collection, what it's collection id, field, type and value? thank you so much!

`Firestore Database` > `Start collection` > Collection ID: `admin` > Document ID: paste the `User UID` from `Authentication > Users` tab > `Save`
